"""Fix updated column

Revision ID: 0f904d455ddd
Revises: ba460ed3c13e
Create Date: 2020-07-01 09:12:44.172085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f904d455ddd'
down_revision = 'ba460ed3c13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'created_at')
    op.drop_column('addresses', 'updated_at')
    op.add_column('addresses',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('addresses',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    op.drop_column('alerts', 'created_at')
    op.drop_column('alerts', 'updated_at')
    op.add_column('alerts',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('alerts',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    op.drop_column('alert_types', 'created_at')
    op.drop_column('alert_types', 'updated_at')
    op.add_column('alert_types',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('alert_types',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    op.drop_column('groups', 'created_at')
    op.drop_column('groups', 'updated_at')
    op.add_column('group',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('groups',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    op.drop_column('home_hubs', 'created_at')
    op.drop_column('home_hubs', 'updated_at')
    op.add_column('home_hubs',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('home_hubs',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    op.drop_column('logins', 'created_at')
    op.drop_column('logins', 'updated_at')
    op.add_column('logins',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('logins',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    op.drop_column('meters', 'created_at')
    op.drop_column('meters', 'updated_at')
    op.add_column('meters',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('meters',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'updated_at')
    op.add_column('notifications',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('notifications',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    op.drop_column('pvs', 'created_at')
    op.drop_column('pvs', 'updated_at')
    op.add_column('pvs',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('pvs',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    op.drop_column('service_locations', 'created_at')
    op.drop_column('service_locations', 'updated_at')
    op.add_column('service_locations',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('service_locations',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    op.drop_column('utilities', 'created_at')
    op.drop_column('utilities', 'updated_at')
    op.add_column('utilities',
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))
    op.add_column('utilities',
        sa.Column('created_at', sa.TIMESTAMP, nullable=True, server_default=sa.func.now()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('addresses', 'created_at')
    op.drop_column('addresses', 'updated_at')
    op.add_column('addresses', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('addresses', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    op.drop_column('alerts', 'created_at')
    op.drop_column('alerts', 'updated_at')
    op.add_column('alerts', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('alerts', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    op.drop_column('alert_types', 'created_at')
    op.drop_column('alert_types', 'updated_at')
    op.add_column('alert_types', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('alert_types', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    op.drop_column('groups', 'created_at')
    op.drop_column('groups', 'updated_at')
    op.add_column('groups', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('groups', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    op.drop_column('home_hubs', 'created_at')
    op.drop_column('home_hubs', 'updated_at')
    op.add_column('home_hubs', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('home_hubs', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    op.drop_column('logins', 'created_at')
    op.drop_column('logins', 'updated_at')
    op.add_column('logins', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('logins', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    op.drop_column('meters', 'created_at')
    op.drop_column('meters', 'updated_at')
    op.add_column('meters', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('meters', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'updated_at')
    op.add_column('notifications', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('notifications', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    op.drop_column('pvs', 'created_at')
    op.drop_column('pvs', 'updated_at')
    op.add_column('pvs', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('pvs', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    op.drop_column('service_locations', 'created_at')
    op.drop_column('service_locations', 'updated_at')
    op.add_column('service_locations', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('service_locations', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    op.drop_column('utilities', 'created_at')
    op.drop_column('utilities', 'updated_at')
    op.add_column('utilities', 
        sa.Column('created_at', sa.TIMESTAMP, nullable=False))
    op.add_column('utilities', 
        sa.Column('updated_at', sa.TIMESTAMP, nullable=False))

    # ### end Alembic commands ###
