"""Adding unique constraint to role_id and user_id in group

Revision ID: 1e25fb61d83f
Revises: 2fba1c751886
Create Date: 2020-06-16 15:09:01.480988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e25fb61d83f'
down_revision = '2fba1c751886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_role_user_uc', 'groups', ['role_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_role_user_uc', 'groups', type_='unique')
    # ### end Alembic commands ###
