"""Added MeterType check_value method, created_at/updated_at columns on meter, address, and service location, put in default parameters on interval_count method

Revision ID: 214395752353
Revises: b9846801dce0
Create Date: 2020-04-30 11:19:20.562773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '214395752353'
down_revision = 'b9846801dce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('addresses', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.drop_column('addresses', 'last_update')
    op.add_column('meters', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('meters', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.alter_column('meters', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('meters', 'is_archived',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.add_column('service_locations', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('service_locations', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_locations', 'updated_at')
    op.drop_column('service_locations', 'created_at')
    op.alter_column('meters', 'is_archived',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('meters', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('meters', 'updated_at')
    op.drop_column('meters', 'created_at')
    op.add_column('addresses', sa.Column('last_update', mysql.TIMESTAMP(), nullable=False))
    op.drop_column('addresses', 'updated_at')
    op.drop_column('addresses', 'created_at')
    # ### end Alembic commands ###
