"""Checking for changes to database

Revision ID: 2312d67686b8
Revises: 6c1f74aad2c4
Create Date: 2020-06-16 11:44:07.373315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2312d67686b8'
down_revision = '6c1f74aad2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'address_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'address_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
