"""Added unique=True for one-to-one relationship foreign keys

Revision ID: 2fba1c751886
Revises: 2312d67686b8
Create Date: 2020-06-16 13:25:16.610929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fba1c751886'
down_revision = '2312d67686b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'home_hubs', ['service_location_id'])
    op.create_unique_constraint(None, 'pvs', ['home_hub_id'])
    op.create_unique_constraint(None, 'pvs', ['meter_id'])
    op.create_unique_constraint(None, 'service_locations', ['address_id'])
    op.create_unique_constraint(None, 'users', ['address_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'service_locations', type_='unique')
    op.drop_constraint(None, 'pvs', type_='unique')
    op.drop_constraint(None, 'pvs', type_='unique')
    op.drop_constraint(None, 'home_hubs', type_='unique')
    # ### end Alembic commands ###
