"""added NotificationEvent, NotificationSubscription, and UtilityNotificationSetting models

Revision ID: 45d9ded81573
Revises: 95029616b0fd
Create Date: 2020-06-29 01:11:44.169674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d9ded81573'
down_revision = '95029616b0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('CAPACITY_BOUNDS', 'PRICE_ALERTS', 'TELECOMM_ALERTS', 'RESOURCE_DEPLETION', name='alerttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'RESOLVED', name='status'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.utility_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('utility_notification_settings',
    sa.Column('utility_notification_setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('YELLOW_ALARM_LOAD', 'RED_ALARM_LOAD', 'YELLOW_ALARM_PRICE', 'RED_ALARM_PRICE', 'PRICE_ALERTS', 'IMPORT_CAPACITY', 'EXPORT_CAPACITY', 'RESOURCE_DEPLETION', 'TELECOMM_ALERTS', name='notificationtype'), nullable=False),
    sa.Column('limit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.utility_id'], ),
    sa.PrimaryKeyConstraint('utility_notification_setting_id'),
    sa.UniqueConstraint('utility_id', 'notification_type', name='_utility_notification_uc')
    )
    op.create_table('notification_events',
    sa.Column('notification_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('utility_notification_setting_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Enum('TRANSFORMER', 'FEEDER', 'RETAIL_MARKET', 'NONE', name='contexttype'), nullable=False),
    sa.Column('context_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.utility_id'], ),
    sa.ForeignKeyConstraint(['utility_notification_setting_id'], ['utility_notification_settings.utility_notification_setting_id'], ),
    sa.PrimaryKeyConstraint('notification_event_id')
    )
    op.create_table('notification_subscriptions',
    sa.Column('notification_subscription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('utility_notification_setting_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.utility_id'], ),
    sa.ForeignKeyConstraint(['utility_notification_setting_id'], ['utility_notification_settings.utility_notification_setting_id'], ),
    sa.PrimaryKeyConstraint('notification_subscription_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_subscriptions')
    op.drop_table('notification_events')
    op.drop_table('utility_notification_settings')
    op.drop_table('alerts')
    # ### end Alembic commands ###
