"""empty message

Revision ID: 45e7d5ba4a86
Revises: dd769894c5e1
Create Date: 2021-11-08 22:19:19.205728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e7d5ba4a86'
down_revision = 'dd769894c5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_setting', sa.Column('resource_depletion', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_setting', 'resource_depletion')
    # ### end Alembic commands ###
