"""empty message

Revision ID: 481042425c40
Revises: d43ad8dd0638
Create Date: 2020-08-31 15:12:28.539349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '481042425c40'
down_revision = 'd43ad8dd0638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'transformers',
        sa.Column('transformer_id',
                  sa.Integer(),
                  autoincrement=True,
                  nullable=False),
        sa.Column('feeder', sa.String(length=45), nullable=False),
        sa.Column('capacity', sa.Integer(), nullable=False),
        sa.Column('updated_at',
                  sa.TIMESTAMP(),
                  server_default=sa.text(
                      'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                  nullable=False),
        sa.Column('created_at',
                  sa.TIMESTAMP(),
                  server_default=sa.text('now()'),
                  nullable=True), sa.PrimaryKeyConstraint('transformer_id'))
    op.alter_column('markets',
                    'created_at',
                    existing_type=mysql.TIMESTAMP(),
                    nullable=True)
    op.add_column('meters',
                  sa.Column('transformer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meters', 'transformers', ['transformer_id'],
                          ['transformer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meters', type_='foreignkey')
    op.drop_column('meters', 'transformer_id')
    op.alter_column('markets',
                    'created_at',
                    existing_type=mysql.TIMESTAMP(),
                    nullable=False)
    op.drop_table('transformers')
    # ### end Alembic commands ###
