"""Added p_bid, q_bid, and mode to meter_interval table

Revision ID: 4adac4773394
Revises: 82d593e573d1
Create Date: 2020-06-14 23:33:02.410008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4adac4773394'
down_revision = '82d593e573d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_intervals', sa.Column('mode', sa.Boolean(create_constraint=True), default=0, nullable=False))
    op.add_column('meter_intervals', sa.Column('p_bid', sa.Float(), default=0, nullable=False))
    op.add_column('meter_intervals', sa.Column('q_bid', sa.Float(), default=0, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meter_intervals', 'q_bid')
    op.drop_column('meter_intervals', 'p_bid')
    op.drop_column('meter_intervals', 'mode')
    # ### end Alembic commands ###
