"""Add channel table

Revision ID: 51f08368519f
Revises: 214395752353
Create Date: 2020-05-08 14:58:39.193079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f08368519f'
down_revision = '214395752353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('setting', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.meter_id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channels')
    # ### end Alembic commands ###
