"""Add Channels

Revision ID: 57f205770aa8
Revises: 214395752353
Create Date: 2020-05-07 12:08:22.798576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f205770aa8'
down_revision = '214395752353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.String(length=64), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('service_location_id', sa.String(length=64), nullable=False),
    sa.Column('setting', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['meter_id', 'utility_id', 'service_location_id'], ['meters.meter_id', 'meters.utility_id', 'meters.service_location_id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channels')
    # ### end Alembic commands ###
