"""empty message

Revision ID: 60d6037df948
Revises: c47373e685e2
Create Date: 2021-09-28 18:51:33.397954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60d6037df948'
down_revision = 'c47373e685e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transformer_intervals', 'end_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('transformer_intervals', 'export_capacity',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('transformer_intervals', 'q',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('transformer_intervals', 'start_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('transformer_intervals', 'unresp_load',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transformer_intervals', 'unresp_load',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('transformer_intervals', 'start_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('transformer_intervals', 'q',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('transformer_intervals', 'export_capacity',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('transformer_intervals', 'end_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
