"""Added market and market interval tables

Revision ID: 6a5b62b5a262
Revises: 1e25fb61d83f
Create Date: 2020-06-18 09:57:34.051052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5b62b5a262'
down_revision = '1e25fb61d83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('market_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('p_max', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('market_id')
    )
    op.create_table('market_intervals',
    sa.Column('market_interval_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('p_exp', sa.Float(), nullable=False),
    sa.Column('p_dev', sa.Float(), nullable=False),
    sa.Column('p_clear', sa.Float(), nullable=False),
    sa.Column('q_clear', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.market_id'], ),
    sa.PrimaryKeyConstraint('market_interval_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_intervals')
    op.drop_table('markets')
    # ### end Alembic commands ###
