"""removed status on meter_interval, added is_bid column on meter_interval, added is_active/is_archived on service_location

Revision ID: 6c1f74aad2c4
Revises: 4adac4773394
Create Date: 2020-06-15 13:16:13.536335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c1f74aad2c4'
down_revision = '4adac4773394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_intervals', sa.Column('is_bid', sa.Boolean(), default=False, nullable=False))
    op.drop_column('meter_intervals', 'status')
    op.add_column('service_locations', sa.Column('is_active', sa.Boolean(), default=False, nullable=False))
    op.add_column('service_locations', sa.Column('is_archived', sa.Boolean(), default=False, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_locations', 'is_archived')
    op.drop_column('service_locations', 'is_active')
    op.add_column('meter_intervals', sa.Column('status', mysql.ENUM('VALID', 'INVALID'), nullable=False))
    op.drop_column('meter_intervals', 'is_bid')
    # ### end Alembic commands ###
