"""added home hub, pv table, connection from pv to meter, added autoincrement service_location_id

Revision ID: 82d593e573d1
Revises: 3e7ea9bdacbb
Create Date: 2020-06-10 21:47:47.740274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# from sqlalchemy.inspection import inspect
from web.models.service_location import ServiceLocation
# revision identifiers, used by Alembic.
revision = '82d593e573d1'
down_revision = '3e7ea9bdacbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_hubs',
    sa.Column('home_hub_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_location_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(create_constraint=False), nullable=False),
    sa.Column('is_archived', sa.Boolean(create_constraint=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['service_location_id'], ['service_locations.service_location_id'], ),
    sa.PrimaryKeyConstraint('home_hub_id')
    )
    op.create_table('meter_intervals',
    sa.Column('meter_interval_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'INVALID', name='status'), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('e', sa.Float(), nullable=False),
    sa.Column('qtmp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.meter_id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.rate_id'], ),
    sa.PrimaryKeyConstraint('meter_interval_id')
    )
    op.create_table('pvs',
    sa.Column('pv_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('home_hub_id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('q_rated', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(create_constraint=False), nullable=False),
    sa.Column('is_archived', sa.Boolean(create_constraint=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['home_hub_id'], ['home_hubs.home_hub_id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.meter_id'], ),
    sa.PrimaryKeyConstraint('pv_id')
    )
    op.drop_table('intervals')
    op.add_column('meters', sa.Column('home_hub_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meters', 'home_hubs', ['home_hub_id'], ['home_hub_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meters', 'home_hub_id')
    op.create_table('intervals',
    sa.Column('interval_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meter_id', mysql.INTEGER(), nullable=False),
    sa.Column('rate_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('VALID', 'INVALID'), nullable=False),
    sa.Column('start_time', mysql.TIMESTAMP(), nullable=False),
    sa.Column('end_time', mysql.TIMESTAMP(), nullable=False),
    sa.Column('value', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.meter_id'], name='intervals_ibfk_3'),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.rate_id'], name='intervals_ibfk_2'),
    sa.PrimaryKeyConstraint('interval_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('pvs')
    op.drop_table('meter_intervals')
    op.drop_table('home_hubs')
    # ### end Alembic commands ###
