"""empty message

Revision ID: 8cc7f5477f98
Revises: bc1c1ff1f203
Create Date: 2020-11-17 12:08:56.490674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc7f5477f98'
down_revision = 'bc1c1ff1f203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_1', table_name='users', type_='foreignkey')
    op.drop_index('address_id', table_name='users')
    op.create_foreign_key('fk_user_address', 'users', 'addresses', ['address_id'], ['address_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_address', table_name='users', type_='foreignkey')
    op.create_index('address_id', 'users', ['address_id'], unique=True)
    op.create_foreign_key('users_ibfk_1', 'users', 'addresses', ['address_id'], ['address_id'])
    # ### end Alembic commands ###
