"""Initial TESS migration.

Revision ID: b9846801dce0
Revises: 
Create Date: 2020-04-24 14:50:50.937893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9846801dce0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('address2', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('last_update', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('rates',
    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('rate_id')
    )
    op.create_table('utilities',
    sa.Column('utility_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('subscription_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('subscription_end', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('utility_id')
    )
    op.create_table('service_locations',
    sa.Column('service_location_id', sa.String(length=64), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('map_location', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.address_id'], ),
    sa.PrimaryKeyConstraint('service_location_id')
    )
    op.create_table('meters',
    sa.Column('meter_id', sa.String(length=64), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('service_location_id', sa.String(length=64), nullable=False),
    sa.Column('feeder', sa.String(length=45), nullable=False),
    sa.Column('substation', sa.String(length=45), nullable=False),
    sa.Column('meter_type', sa.Enum('one', 'two', 'three', name='metertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(create_constraint=False), nullable=True),
    sa.Column('is_archived', sa.Boolean(create_constraint=False), nullable=True),
    sa.ForeignKeyConstraint(['service_location_id'], ['service_locations.service_location_id'], ),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.utility_id'], ),
    sa.PrimaryKeyConstraint('meter_id', 'utility_id', 'service_location_id')
    )
    op.create_table('intervals',
    sa.Column('interval_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.String(length=64), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('service_location_id', sa.String(length=64), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('one', name='status'), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id', 'utility_id', 'service_location_id'], ['meters.meter_id', 'meters.utility_id', 'meters.service_location_id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.rate_id'], ),
    sa.PrimaryKeyConstraint('interval_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervals')
    op.drop_table('meters')
    op.drop_table('service_locations')
    op.drop_table('utilities')
    op.drop_table('rates')
    op.drop_table('addresses')
    # ### end Alembic commands ###
