"""empty message

Revision ID: bc1c1ff1f203
Revises: 12cc25809a52
Create Date: 2020-10-20 12:06:30.702420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1c1ff1f203'
down_revision = '12cc25809a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformer_intervals',
    sa.Column('transformer_interval_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transformer_id', sa.Integer(), nullable=False),
    sa.Column('import_capacity', sa.Float(), nullable=False),
    sa.Column('export_capacity', sa.Float(), nullable=False),
    sa.Column('q', sa.Float(), nullable=False),
    sa.Column('unresp_load', sa.Float(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.transformer_id'], ),
    sa.PrimaryKeyConstraint('transformer_interval_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transformer_intervals')
    # ### end Alembic commands ###
