"""empty message

Revision ID: c47373e685e2
Revises: 8cc7f5477f98
Create Date: 2021-06-22 15:05:24.694489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c47373e685e2'
down_revision = '8cc7f5477f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_intervals', sa.Column('mode_dispatch', sa.Float(), nullable=False))
    op.add_column('meter_intervals', sa.Column('mode_market', sa.Float(), nullable=False))
    op.drop_column('meter_intervals', 'mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_intervals', sa.Column('mode', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('meter_intervals', 'mode_market')
    op.drop_column('meter_intervals', 'mode_dispatch')
    # ### end Alembic commands ###
