"""rearrange foreign key on interval

Revision ID: c7ebb23a675d
Revises: 51f08368519f
Create Date: 2020-05-08 21:22:00.336415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7ebb23a675d'
down_revision = '51f08368519f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('intervals_ibfk_1', 'intervals', type_='foreignkey')
    op.create_foreign_key(None, 'intervals', 'meters', ['meter_id'], ['meter_id'])
    op.drop_column('intervals', 'utility_id')
    op.drop_column('intervals', 'service_location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervals', sa.Column('service_location_id', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('intervals', sa.Column('utility_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'intervals', type_='foreignkey')
    op.create_foreign_key('intervals_ibfk_1', 'intervals', 'meters', ['meter_id', 'utility_id', 'service_location_id'], ['meter_id', 'utility_id', 'service_location_id'])
    # ### end Alembic commands ###
