"""Add market id foreign key to Home Hub

Revision ID: e7763a323f0d
Revises: 6a5b62b5a262
Create Date: 2020-06-18 12:31:30.935718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7763a323f0d'
down_revision = '6a5b62b5a262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_hubs', sa.Column('market_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'home_hubs', 'markets', ['market_id'], ['market_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'home_hubs', type_='foreignkey')
    op.drop_column('home_hubs', 'market_id')
    # ### end Alembic commands ###
